### ISSUE TITLE
Add a color for editor.selectionHighlightBackground

### ISSUE THREAD

**Issue by BradCOnGitHub** [akamud/vscode-theme-onelight#10]
The default for editor.selectionHighlightBackground is nearly the same color as the background color in this theme. I actually thought my selection highlighting was broken until I figured this out.

This is what I'm using but maybe you can find a better color:

    "workbench.colorCustomizations": {
        "editor.selectionHighlightBackground": "#92c0a5"
    },

**Comment by akamud** [comment]
Hi @BradCOnGitHub, thanks for submitting this.

This is something I want to review to see if it is matching Atom exactly. Thanks for sending your customization, I'll let you know if I change the selected color so you can remove your customization.

**Comment by akamud** [comment]
This doesn't match the same color from Atom. In 2.2.0, the selection color is the same in Atom. Of course you can customize as you are doing it already for a green color.
