### ISSUE TITLE
The color highlighting is very far from Atom theme

### ISSUE THREAD

**Issue by eugenet8k** [akamud/vscode-theme-onelight#13]
Moving to the VS Code and found your awesome theme. But it seems it's extremely flaky.

## Sample code

```js
const _ = require('lodash')
const webpackConfig = require('./webpack.config.dev')

const isBrowserStack = !!process.env.BROWSERSTACK_RUN || false
const isDebugMode = !!process.env.DEBUG || false
const reportHtmlCoverage = !!process.env.HTML_COVERAGE || false
const skipTargets = _.toLower(process.env.SKIP_BROWSERSTACK_TARGETS).split('|')
process.env.CHROME_BIN = require('puppeteer').executablePath()

const browserStackBrowsers = _.map(
  _.difference(['chrome', 'edge', 'ie', 'firefox', 'safari'], skipTargets),
  b => `${b}_latest`
)

const createLauncher = options => ({
  base: 'BrowserStack',
  os: 'Windows',
  os_version: '10',
  ...options
})

const webpack = {
  ..._.omit(webpackConfig, ['entry', 'output']),
  devtool: 'inline-source-map',
  module: {
    ...webpackConfig.module,
    rules: _.compact([
      !isBrowserStack && {
        test: /\.coffee|\.js$/,
        enforce: 'post',
        exclude: /node_modules|\.spec\.coffee|\.spec\.js$/,
        use: {
          loader: 'istanbul-instrumenter-loader',
          options: {esModules: true, produceSourceMap: isDebugMode}
        }
      },
      ...webpackConfig.module.rules,
      {
        test: /\.(png|svg|woff|woff2|eot|ttf)$/,
        exclude: /node_modules(?!\/@gnosis)/,
        loader: 'null-loader'
      },
      !(isBrowserStack || isDebugMode) && {
        enforce: 'pre',
        test: /\.hbs/,
        loader: 'htmlhint-loader',
        exclude: /node_modules/,
        options: {
          failOnError: true,
          outputReport: true
        }
      }
    ])
  }
}

```

## Filename and Language selected

karma.conf.js

## Atom Original theme Screenshot
<img width="660" alt="Screenshot 2019-10-22 15 24 57" src="https://user-images.githubusercontent.com/4804824/67339693-90297b00-f4e0-11e9-99de-cd1b4e3df859.png">

## VSCode theme Screenshot
<img width="664" alt="Screenshot 2019-10-22 15 25 20" src="https://user-images.githubusercontent.com/4804824/67339733-9ddf0080-f4e0-11e9-99be-f567c7ba8b1a.png">

## Versions used

* VSCode version: 1.39.2
* Theme version: 2.1.0

## Extra information

I am using all default VS Code plugins.  I noticed that generally the coloring of module imports is different is it's `requirejs` or `ES imports`

**Comment by akamud** [comment]
This is much better now in 2.2.0.

![image](https://user-images.githubusercontent.com/954102/76755700-1336c080-6763-11ea-89e0-84f6badb8064.png)

Please remember to disable Semantic Highlighting if you are using VSCode 1.43.0 with One Light 2.2.0:

```js
"editor.semanticHighlighting.enabled": false
```

Unfortunately, regarding the const/variables, that is something that [gets asked a lot](https://github.com/akamud/vscode-theme-onelight/issues/11) but isn't possible to fix right now in VSCode.
A new semantic highlighting is coming that should make it possible to finally have the correct colors for const/variables. I'm working on this support for 3.0.0.

**Comment by eugenet8k** [comment]
Thank you @akamud, I've updated the theme and turned off `semanticHighlighting` and it looks great now! I appreciate all the support!

**Comment by akamud** [comment]
Thanks. I plan to investigate the regex differences in a future release too.
