### ISSUE TITLE
console word color

### ISSUE THREAD

**Issue by monsieurm** [akamud/vscode-theme-onelight#20]
Hi

Since 1.48 (I guess) in .js files, the word console in console.log for example is white. Before it was yellow and more visible.

I run the 1.48.2 update but there is always this issue.
I have set "semanticHighlighting": "true", "false", and "configuredByTheme", same issue.

Have you and idea to fix this ?

Thanks

* VSCode version: 1.48.2
* Theme version: 2.2.2

**Comment by akamud** [comment]
Thanks for bringing this to my attention. Indeed something broke in 1.48.2, it no longer recognizes console as the correct scope.

![image](https://user-images.githubusercontent.com/954102/91671565-41843e80-eafe-11ea-9de8-22e6cdf19d71.png)

I'll get back to you as soon as I find more information.

**Comment by akamud** [comment]
VSCode [claims](https://github.com/microsoft/vscode/issues/104616) the console showing a different color was the wrong behavior and that they fixed it now. So I just can't make it become the same color as before without breaking a whole bunch of stuff in the process, at least not without an update from the TS or VSCode team.

All we can do is open an issue for the TS lang team asking them to make the tokenize `console` with something unique, as mentioned [here](https://github.com/microsoft/vscode/issues/104616#issuecomment-675066291).

**Comment by akamud** [comment]
I'm closing this for now, if VSCode/TS ever changes that, feel free to reopen this issue so we can discuss. For now it can't be "fixed" and I'm afraid there is no way of working around this without changing other tokens.
