### ISSUE TITLE
How to change JSX colors?

### ISSUE THREAD

**Issue by mrousavy** [akamud/vscode-theme-onelight#22]
Hi! I've recently switched from the atom one dark to the atom one light theme, and while I love 99% of the theme, I dislike the colors of the JSX tree.

See, this screenshot:

![image](https://user-images.githubusercontent.com/15199031/99063862-718f9980-25a5-11eb-8628-bf32d219742d.png)

The actual tags (e.g. `<View`) don't have enough contrast to the individual properties (e.g. `style`) - I've tried different combinations and looked through my theme settings to find out how I can tweak this, but I couldn't find the right setting. Using the color meter I've picked `#c88f01`, not sure if that's the actual color though.

How can I change these colors?

## Sample code

```tsx
export function App() {
  return (<View style={{ flex: 1 }}></View>);
}
```

## Filename and Language selected

`.tsx`, TypeScript + React. I'm assuming this also applies to JS + React, so `.jsx` or `.js`.

## Versions used

* VSCode version: 1.52.0-insider Commit: ee46c1f89ebb213e0827886f1688c0fbb55be49f
* Theme version: 2.2.2

**Comment by akamud** [comment]
Hi there, it is possible to customize every color from a theme in Code, following [these instructions](https://code.visualstudio.com/api/references/theme-color).

You just need to find the right _scope_ to apply the customizations to. To do that, you must put your cursor on the desired word and trigger the `Developer: Inspect Editor Tokens and Scopes` action.
You should see this window telling you the `textmate scopes` that you should use.

![image](https://user-images.githubusercontent.com/954102/103586675-57e34200-4ec4-11eb-8df7-2746e2ca1374.png)
![image](https://user-images.githubusercontent.com/954102/103586745-806b3c00-4ec4-11eb-9ae8-f2ffe34b2824.png)

From the above screenshots you can see that using `support.class.component.js.jsx` should probably customize only the component name's color without affecting anything else.
