### ISSUE TITLE
rust backgroup ugly

### ISSUE THREAD

**Issue by greyireland** [akamud/vscode-theme-onelight#29]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code
![image](https://user-images.githubusercontent.com/9276742/187410123-f27f76dc-dfa4-45c7-9807-6e0813248393.png)
![image](https://user-images.githubusercontent.com/9276742/187410834-ab10b36e-d729-4f7c-a2dd-ce463ddc98ef.png)

want this 
![image](https://user-images.githubusercontent.com/9276742/187410734-57259454-70af-456e-abb7-4fb38c87227a.png)

Remove the font blue background, or dim the font background. The blue background is too conspicuous and interferes with the core code flow

**Comment by greyireland** [comment]
I hope the blue background will be consistent with the color of the annotation

**Comment by greyireland** [comment]
If you can tell me how to modify it to achieve this goal, it's OK

**Comment by greyireland** [comment]
![image](https://user-images.githubusercontent.com/9276742/187413430-4f28cce3-e1a1-45ff-b482-0a3a0784c00f.png)

**Comment by akamud** [comment]
This should be fixed in 2.3.0.
