### ISSUE TITLE
This updata is not so good ...

### ISSUE THREAD

**Issue by webCoderJ** [akamud/vscode-theme-onelight#5]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code

```
[Please provide a code snippet so I can test]
```

## Filename and Language selected

[Please tell us which file extension are you editing and which language VSCode is using for this file]

## Atom Original theme Screenshot

[Screenshot of your code inside Atom, under same conditions, showing how the coloring should look]

## VSCode theme Screenshot

[VSCode screeshot showing how the coloring is]

## Versions used

* VSCode version: 1.13.0
* Theme version: 2.0.1

## Extra information

[Any other information that might be useful]  
[Are you using a Plugin? Some languages (like Rust) require a plugin from the Marketplace to work on VSCode, please tell us if you are using any plugins that can be affecting the way VSCode renders your code]

my sidebar changed to white and the bgcolor of the filemanager is too dark , I think the previous version is perfect. how can i get it ? thanks very much!

**Comment by webCoderJ** [comment]
![d9456645-7876-4104-9634-3fee1b5c15e9](https://user-images.githubusercontent.com/19652730/26959357-5b1ceb46-4d02-11e7-96be-a8bfc7cefc04.png)

This is my vscode screenshot

**Comment by akamud** [comment]
I'm sorry, I'm not sure what you mean.

In 2.0 I now support full workbench theming, as close to "One Light" theme from Atom as possible.

Do you mean you want the workbench as it were before? If so, please take a look at #3, I think it will be useful for you.

**Comment by webCoderJ** [comment]
OOOOH, Im very sorry about it, my english is  so poor.

The workbench support is very wonderful, but i feel that the colors In workbench were not so harmonize, so i want it were before.

Thank you 



发自我的 iPhone

**Comment by akamud** [comment]
It's okay.

Then take a look at #3, I provide a customization you can apply to your VSCode to make it have the same colors as before. You just have to paste in your _Settings_, under `"workbench.colorCustomizations"`.
