### ISSUE TITLE
feat: Operator mono support

### ISSUE THREAD

**Issue by d3viant0ne** [akamud/vscode-theme-onelight#9]
> First light theme in 21 years I have ever liked

Figured I'd bring this here before modifying a fork. Only thing I am missing, this particular theme doesn't take advantage of Operator which is something I have grown quite fond of.

If your interested, I can PR that in here. If not, I can simply modify a fork. Totally up to you.

**Comment by akamud** [comment]
Do you mean the Operator Mono font? If that is the case, my theme doesn' actually force any kind of fonts nor prevents you from using it.

You can easily customize this in VSCode using `"editor.fontFamily": "Your font"`. For example, I use `Fira Code`, so I just use `"editor.fontFamily": "Fira Code, Consolas, 'Courier New', monospace"` and it works with any theme.

**Comment by d3viant0ne** [comment]
For reference, I was talking about leveraging the fonts options to this sort of effect ...

![screen shot 2017-10-06 at 12 58 52 pm](https://user-images.githubusercontent.com/8420490/31291683-34c7f69c-aa96-11e7-926c-1517fd892a42.png)

**Comment by akamud** [comment]
Oh I see, this has been asked before. But at the moment I don't plan on doing that, since this is a direct port from Atom theme itself, I don't plan on adding any extra features at the moment.
